import { StyleSheet } from 'react-native';
import { back } from 'react-native/Libraries/Animated/Easing';

const estilo = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        margin: 10,
        marginTop: 20,
        marginBottom: 20,
    },
    card: {
        marginLeft: 10,
        marginRight: 10,
        borderRadius: 15,
        backgroundColor: '#7D3030',
        padding: 10,
        marginBottom: 15,
        minHeight: 80,
        maxHeight: 160,
        width: 320,
    },
    img: {
        width: 320,
        height: 320,
        margin: 5,
        borderWidth: 1,
        borderRadius: 25,
        borderColor: 'black',
        marginBottom: 15,
    },
    titulo: {
        fontSize: 19,
        color: '#fff',
        fontFamily: 'principal',
    },
    paragrafo: {
        fontSize: 16,
        textAlign: 'justify',
        color: '#fff',
        fontFamily: 'paragrafos',
        letterSpacing: 1,
        minWidth: '29%',
        maxWidth: '33%',
        marginLeft: 18,
    },
    paragrafoSobre: {
        fontSize: 16,
        textAlign: 'justify',
        color: '#fff',
        fontFamily: 'paragrafos',
        letterSpacing: 1,
        minWidth: '29%',
        maxWidth: '100%',
        marginLeft: 0,
    },
    paragrafoDanoGrande: {
        fontSize: 16,
        textAlign: 'justify',
        color: '#fff',
        fontFamily: 'paragrafos',
        letterSpacing: 1,
        minWidth: '29%',
        maxWidth: '33%',
        marginLeft: 2,
        marginRight: 20,
    },
    paragrafoTipo: {
        fontSize: 14,
        textAlign: 'justify',
        color: '#fff',
        fontFamily: 'paragrafos',
        letterSpacing: 1,
        minWidth: '29%',
        maxWidth: '33%',
        marginLeft: 6,
    },
    paragrafoPeso: {
        fontSize: 16,
        textAlign: 'justify',
        color: '#fff',
        fontFamily: 'paragrafos',
        letterSpacing: 1,
        minWidth: '29%',
        maxWidth: '33%',
        marginLeft: 10,
    },
    topico: {
        fontSize: 15,
        color: 'yellow',
        fontFamily: 'principal',
        marginTop: 10,
        margin: 18,
        marginBottom: 1,
    },
    topicoSobre: {
        fontSize: 15,
        color: 'yellow',
        fontFamily: 'principal',
        marginTop: 10,
        margin: 18,
        marginBottom: 1,
        marginLeft: 0,
    },
    topicoSobre: {
        fontSize: 15,
        color: 'yellow',
        fontFamily: 'principal',
        marginTop: 10,
        margin: 18,
        marginBottom: 1,
        marginLeft: 0,
    },
    topicoPeso: {
        fontSize: 15,
        color: 'yellow',
        fontFamily: 'principal',
        marginTop: 10,
        margin: 18,
        marginBottom: 1,
        marginLeft: 1,
        marginRight: 28,
    },
    categoria: {
        fontSize: 26,
        fontFamily: 'principal',
        color: 'black',
        marginTop: 10,
        marginBottom: 10,
        textAlign: 'center',
    },
    descricao: {
        fontSize: 10,
        marginBottom: 10,
        fontFamily: 'principal',
        textAlign: 'center'
    },
    requisito: {
        fontSize: 12,
        color: 'yellow',
        fontFamily: 'principal',
        marginTop: 10,
    },
    cardtabela: {

        width: 320,
        borderWidth: 1,
        borderRadius: 25,
        borderColor: 'black',
        marginBottom: 20,
    },
    linhaCinza: {
        backgroundColor: '#d6cfca',
        flexDirection: 'row',
        padding: 5,
    },
    linhaCinzaTopo: {
        backgroundColor: '#d6cfca',
        flexDirection: 'row',
        borderWidth: 0,
        borderTopRightRadius: 25,
        borderTopLeftRadius: 25,
        padding: 5,
    },
    linhaCinzaFinal: {
        backgroundColor: '#d6cfca',
        flexDirection: 'row',
        borderWidth: 0,
        borderBottomRightRadius: 25,
        borderBottomLeftRadius: 25,
        padding: 5,
    },
    linhaBranca: {
        backgroundColor: '#f5f5f4',
        flexDirection: 'row',
        padding: 5,
    },
    paragrafoPreto: {
        fontSize: 11,
        textAlign: 'center',
        color: 'black',
        fontFamily: 'paragrafos',
        letterSpacing: 1,
        maxWidth: 240,
        marginLeft: 80,
    },
    paragrafoPretoNivel: {
        fontSize: 11,
        textAlign: 'center',
        color: 'black',
        fontFamily: 'paragrafos',
        letterSpacing: 1,
        width: '20%'
    },
    paragrafoPretoNivelTitulo: {
        fontSize: 12,
        textAlign: 'center',
        color: 'black',
        fontFamily: 'principal',
        letterSpacing: 1,
        width: '18%',
        padding: 5,
    },
    paragrafoPretoDinheiroTitulo: {
        fontSize: 12,
        textAlign: 'center',
        color: 'black',
        fontFamily: 'principal',
        letterSpacing: 1,
        padding: 5,
        marginLeft: 23,
    },
    botao: {
        backgroundColor: '#7D3030',
        borderRadius: 5,
        width: 150,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 10,
        minHeight: 50,
        maxHeight: 100,
        marginVertical: 10,
    },
    texto: {
        fontSize: 20,
        fontFamily: 'principal',
        color: '#fff',
        textAlign: 'center',
    },
    linha: {
        flexDirection: 'row',
        margin: 8,
        width: '100%',
    },
})

export default estilo;